from .cacnn import CACNN
from .cnn_kul import CNN_KUL
from .gcn import GCN
from .stanet import StaNet
from .eegnet import EEGNet
from .eegnet_bnn import EEGNet_bnn
from .resnet import ResNet18
from .inception import INCEPTION
from .pyramidnet import PYRAMIDNET
from .deepnetwork import deepNetwork
from .cnn_lstm import CNN_LSTM